-- Script para criar as tabelas (executado antes do data.sql)

-- Criar tabela categories
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

-- Criar tabela usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    tipo VARCHAR(255)
);

-- Criar tabela products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    price FLOAT(53),
    quantity INTEGER,
    location VARCHAR(255),
    expiry_date VARCHAR(255),
    fornecedor BIGINT,
    image CLOB,
    FOREIGN KEY (fornecedor) REFERENCES usuarios(id)
);

-- Criar tabela carts
CREATE TABLE IF NOT EXISTS carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_price NUMERIC(38,2),
    purchase_date TIMESTAMP(6),
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES usuarios(id)
);

-- Criar tabela cart_items
CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selected_quantity INTEGER,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    FOREIGN KEY (cart_id) REFERENCES carts(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Criar tabela product_categories
CREATE TABLE IF NOT EXISTS product_categories (
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (product_id, category_id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);
